/********************************************************************
* ./src/sgsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/sgsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablesgsCint();
extern void G__cpp_setup_inheritancesgsCint();
extern void G__cpp_setup_typetablesgsCint();
extern void G__cpp_setup_memvarsgsCint();
extern void G__cpp_setup_globalsgsCint();
extern void G__cpp_setup_memfuncsgsCint();
extern void G__cpp_setup_funcsgsCint();
extern void G__set_cpp_environmentsgsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/ScintHitInfo.hh"
#include "../include/WorldSetup.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__sgsCintLN_TClass;
extern G__linked_taginfo G__sgsCintLN_TBuffer;
extern G__linked_taginfo G__sgsCintLN_TMemberInspector;
extern G__linked_taginfo G__sgsCintLN_TObject;
extern G__linked_taginfo G__sgsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__sgsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sgsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__sgsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sgsCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__sgsCintLN_ScintHitInfo;
extern G__linked_taginfo G__sgsCintLN_WorldSetup;

/* STUB derived class for protected member access */
